name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build
        
      - name: Add custom files
        run: |
          # Create .nojekyll file to disable Jekyll processing
          touch out/.nojekyll
          
          # Create a better 404 page with proper redirect
          cat > out/404.html << EOL
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>State of Solana Dashboard</title>
  <script>
    // Redirect to base path with the current URL path appended
    var segmentCount = 1; // Number of segments in path to remove (for repository name)
    var location = window.location;
    var pathname = location.pathname;
    var redirectPath = pathname.split('/').slice(segmentCount + 1).join('/');
    window.location.href = '/state_of_solana/' + redirectPath + location.search + location.hash;
  </script>
</head>
<body>
  <p>Redirecting to State of Solana Dashboard...</p>
</body>
</html>
EOL
          
          # Create root index.html if it doesn't exist
          if [ ! -f out/index.html ]; then
            cat > out/index.html << EOL
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>State of Solana Dashboard</title>
  <script>
    window.location.href = '/state_of_solana/';
  </script>
</head>
<body>
  <p>Redirecting to State of Solana Dashboard...</p>
</body>
</html>
EOL
          fi
          
          # Copy the favicon if it exists
          cp -f app/favicon.ico out/ || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true