name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Update next.config.js for static export
        run: |
          cat > next.config.js << 'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            basePath: '/state_of_solana',
            images: {
              unoptimized: true,
            },
            reactStrictMode: false,
            eslint: {
              ignoreDuringBuilds: true,
            },
            // Exclude API routes from static export
            exportPathMap: async function (
              defaultPathMap,
              { dev, dir, outDir, distDir, buildId }
            ) {
              // Only include non-API routes
              const pathMap = {};
              
              // Add root paths
              pathMap['/'] = { page: '/' };
              pathMap['/dashboard'] = { page: '/dashboard' };
              pathMap['/debug-colors'] = { page: '/debug-colors' };
              
              // Add dex routes
              pathMap['/dex'] = { page: '/dex' };
              pathMap['/dex/aggregators'] = { page: '/dex/aggregators' };
              pathMap['/dex/summary'] = { page: '/dex/summary' };
              pathMap['/dex/traders'] = { page: '/dex/traders' };
              pathMap['/dex/tvl'] = { page: '/dex/tvl' };
              pathMap['/dex/volume'] = { page: '/dex/volume' };
              
              // Add admin routes
              pathMap['/admin'] = { page: '/admin' };
              pathMap['/admin/chart-creator'] = { page: '/admin/chart-creator' };
              pathMap['/admin/manage-charts'] = { page: '/admin/manage-charts' };
              
              // Add other routes
              pathMap['/examples'] = { page: '/examples' };
              pathMap['/market-dynamics'] = { page: '/market-dynamics' };
              pathMap['/network-usage'] = { page: '/network-usage' };
              
              // Protocol revenue routes
              pathMap['/protocol-revenue'] = { page: '/protocol-revenue' };
              pathMap['/protocol-revenue/depin'] = { page: '/protocol-revenue/depin' };
              pathMap['/protocol-revenue/dex-ecosystem'] = { page: '/protocol-revenue/dex-ecosystem' };
              pathMap['/protocol-revenue/nft-ecosystem'] = { page: '/protocol-revenue/nft-ecosystem' };
              pathMap['/protocol-revenue/summary'] = { page: '/protocol-revenue/summary' };
              pathMap['/protocol-revenue/total'] = { page: '/protocol-revenue/total' };
              
              // REV routes
              pathMap['/rev'] = { page: '/rev' };
              pathMap['/rev/cost-capacity'] = { page: '/rev/cost-capacity' };
              pathMap['/rev/issuance-burn'] = { page: '/rev/issuance-burn' };
              pathMap['/rev/total-economic-value'] = { page: '/rev/total-economic-value' };
              
              // Stablecoins routes
              pathMap['/stablecoins'] = { page: '/stablecoins' };
              pathMap['/stablecoins/liquidity-velocity'] = { page: '/stablecoins/liquidity-velocity' };
              pathMap['/stablecoins/mint-burn'] = { page: '/stablecoins/mint-burn' };
              pathMap['/stablecoins/platform-exchange'] = { page: '/stablecoins/platform-exchange' };
              pathMap['/stablecoins/stablecoin-usage'] = { page: '/stablecoins/stablecoin-usage' };
              pathMap['/stablecoins/transaction-activity'] = { page: '/stablecoins/transaction-activity' };
              pathMap['/stablecoins/tvl'] = { page: '/stablecoins/tvl' };
              
              return pathMap;
            },
          };
          
          module.exports = nextConfig;
          EOF
      
      - name: Build
        run: npm run build
        env:
          NEXT_DISABLE_ESLINT: 1
      
      - name: Create .nojekyll
        run: touch out/.nojekyll
      
      - name: Create placeholder API responses
        run: |
          # Create a directory structure for API routes
          mkdir -p out/state_of_solana/api/charts
          
          # Create a sample response for /api/charts
          cat > out/state_of_solana/api/charts/index.html << 'EOF'
          {"charts":[]}
          EOF
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4